cc_binary(
  name = "main",
  srcs = [
    "main.cc",
  ],
  deps = [
    "//proto:dispatch_cc_proto",
    "//proto:dispatch_cc_grpc",
    "@com_github_grpc_grpc//:grpc++",
    "@abseil-cpp//absl/flags:flag",
    "@abseil-cpp//absl/flags:parse",
  ],
)

